name: mumiappfood
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Thêm dòng này
    sdk: flutter         # Thêm dòng này

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0 # THÊM THƯ VIỆN SHIMMER
  flutter_markdown: ^0.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Utils
  intl: 0.20.2
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  geocoding: ^4.0.0
  image_picker: ^1.2.0
  google_maps_flutter: ^2.13.1
  google_places_flutter: ^2.1.1
  cloud_firestore: ^6.0.2
  timeago: ^3.7.1
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  cross_file: ^0.3.3+6
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true # Kích hoạt tính năng tạo mã tự động

  assets:
    - assets/images/branding/
    - assets/images/icon/

# SỬA ĐỔI: Cấu hình lại để sử dụng đúng logo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/branding/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/branding/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/branding/logo.png
  ios: true
  web: false

  # Localization config
  localizations:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
